version: '3.9'

services:
  web:
    build: .
    command: ./wait-for-postgres.sh

    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ipo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: runserver2004
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
