# Generated by Django 5.0.6 on 2025-06-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Open', 'Open'), ('Closed', 'Closed'), ('Listed', 'Listed')], max_length=20)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhp_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('drhp_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ipo_app.ipo')),
            ],
        ),
    ]
