# Generated by Django 5.0.6 on 2025-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0002_alter_company_company_logo_alter_ipo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='company',
        ),
        migrations.AddField(
            model_name='ipo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
