# Generated by Django 5.0.6 on 2025-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0004_remove_ipo_company_name_ipo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], max_length=20),
        ),
    ]
