# Generated by Django 5.0.6 on 2025-07-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0005_alter_ipo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='company',
        ),
        migrations.AddField(
            model_name='ipo',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
    ]
