# Generated by Django 5.0.6 on 2025-07-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0006_remove_ipo_company_ipo_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='company_name',
        ),
        migrations.AddField(
            model_name='ipo',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo_app.company'),
        ),
    ]
