# Generated by Django 5.0.6 on 2025-07-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0008_alter_ipo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
    ]
