# Generated by Django 5.0.6 on 2025-07-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0009_alter_ipo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo_app.company'),
        ),
    ]
