# Generated by Django 5.0.6 on 2025-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0011_alter_ipo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
