# Generated by Django 5.0.6 on 2025-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0012_ipo_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='document',
            name='drhp_pdf',
        ),
        migrations.RemoveField(
            model_name='document',
            name='rhp_pdf',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('RHP', 'RHP'), ('DRHP', 'DRHP')], default='RHP', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='RHP', upload_to='docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='issue_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='issue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='price_band',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='status',
            field=models.CharField(choices=[('coming', 'Coming'), ('newlisted', 'Newlisted'), ('ongoing', 'Ongoing')], max_length=10),
        ),
    ]
